# Generated by Django 2.2.14 on 2022-07-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220708_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
